In [3]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-03 19:34
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-03 19:34
* @Title: :NumPy program to create an array which looks like below array.
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]
"""

import numpy as np
x = np.tri(4, 3, -1)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
