In [1]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-03 19:34
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-03 19:34
* @Title: :NumPy program to change the data type of an array.
"""
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)

#Handling for null values
#Info in dataframe, Discribe
#What kind of graph is when it is used

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
