In [3]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-02 18:00
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-02 18:00
* @Title: :NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
"""
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8), dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
