In [7]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-03 19:46
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-03 19:46
* @Title: :Python program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]
"""

import numpy as np
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), 0)
print(c)

[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]
