In [1]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-03 19:00
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-03 19:00
* @Title: :NumPy program to create a contiguous flattened array.
"""

import numpy as np
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:")
print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]
