In [3]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-03 19:05
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-03 19:05
* @Title: :PPython program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]
"""
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))
print("Unique values in array 2 that are not in array 1:")
print(np.setdiff1d(array2, array1))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]
Unique values in array 2 that are not in array 1:
[30 50 70]
