In [1]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-02 18:20
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-02 18:20
* @Title: :NumPy program to convert a list and tuple into arrays.
"""

import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]
