In [3]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-02 17:40
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-02 17:40
* @Title: :NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
"""

import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
