In [3]:
"""
* @Author: Mohammad Fatha
* @Date: 2021-10-03 19:50
* @Last Modified by: Mohammad Fatha
* @Last Modified time: 2021-10-03 19:50
* @Title: :NumPy program to create an array of (3, 4) shape, multiply every element value by 3 
            and display the new array.
"""

import numpy as np
x= np.arange(12).reshape(3, 4)
print("Original array elements:")
print(x)
for a in np.nditer(x, op_flags=['readwrite']):
    a[...] = 3 * a
# x = x * 3
print("New array elements:")
print(x)

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
